server:
  port: 5000

  servlet:
    jsp:
      init-parameters:
        development: true
       
  
spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
        
  datasource:
#    url: jdbc:mysql://awseb-e-itkedeniwp-stack-awsebrdsdatabase-hxce33xijvv4/teamp?serverTimezone=Asia/Seoul
    url: jdbc:mysql://database.cp66ubjknwwd.ap-northeast-2.rds.amazonaws.com/endP?serverTimezone=Asia/Seoul
    username: root
    password: root1234

#  datasource:
#    url: jdbc:mysql://localhost:3306/teamp
#    username: teamp
#    password: teamp
    
  mvc:
    view:
      prefix: WEB-INF/views/
      suffix: .jsp
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: dabi9365@gmail.com
    password: fumcsybfyadnuups
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
 